import HomePage from "@Container/HomePage/HomePage";
import Head from "next/head";

export default function Home() {
  const [image, setImage] = useState("");
  const uploadImage = async (imageFile) => {
    const data = new FormData();
    data.append("file", imageFile);
    data.append("upload_preset", "itlab_image_store_preset");
    data.append("cloud_name", "dl8hmamey");
    fetch("  https://api.cloudinary.com/v1_1/dl8hmamey/image/upload", {
      method: "post",
      body: data,
    })
      .then((resp) => resp.json())
      .then((data) => {
        console.log("data.url");
        console.log(data.url);
      })
      .catch((err) => console.log(err));
  };
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div>
        <HomePage />
      </div>
    </>
  );
}
